// GENERATED from backend/openapi.yaml — do not edit. Re-sync with: node scripts/sync-medusa-contract.mjs
// Public surface of the Berry Servis Medusa contract.
//
// Source of truth: ../openapi.yaml → medusa-contract.d.ts (generated by
// `npm run gen:contract`). Import the friendly names from here rather than
// reaching into `components["schemas"][...]`. Consumer apps vendor this folder
// via scripts/sync-medusa-contract.mjs.
import type { components } from "./medusa-contract"

type Schemas = components["schemas"]

export type CartItem = Schemas["CartItem"]
export type CustomerInfo = Schemas["CustomerInfo"]
export type B2BMetadata = Schemas["B2BMetadata"]
export type OfficeOrderRequest = Schemas["OfficeOrderRequest"]
export type MedusaVariant = Schemas["MedusaVariant"]
export type MedusaProduct = Schemas["MedusaProduct"]
export type StoreCart = Schemas["StoreCart"]
export type StoreShippingOption = Schemas["StoreShippingOption"]
export type StorePaymentSession = Schemas["StorePaymentSession"]
export type StorePaymentCollection = Schemas["StorePaymentCollection"]
export type CodFeeResponse = Schemas["CodFeeResponse"]
export type SyncPaymentFeeRequest = Schemas["SyncPaymentFeeRequest"]
export type OfficeCartConfirmRequest = Schemas["OfficeCartConfirmRequest"]
export type OfficeCartConfirmResponse = Schemas["OfficeCartConfirmResponse"]
export type NewsletterSubscribeRequest = Schemas["NewsletterSubscribeRequest"]

export type { paths, components } from "./medusa-contract"
